name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base-href ${{ env.BASE_HREF }}
        env:
          API_URL: ${{ secrets.API_URL || 'http://mateusnavarro77.xyz/api/v1' }}
          BASE_HREF: / # Default to root. Update this to '/your-repo-name/' if needed.

      - name: Handle SPA Routing (Copy index.html to 404.html)
        run: cp dist/projeto-cybersec-taskmanager-frontend/browser/index.html dist/projeto-cybersec-taskmanager-frontend/browser/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/projeto-cybersec-taskmanager-frontend/browser
